[package]
name = "bisa"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
fud-core = { version = "0.0.2", git = "https://github.com/calyxir/calyx.git", branch = "rhai-1.19" }
manifest-dir-macros = "0.1.18"

[[bin]]
name = "bisa"
path = "src/main.rs"
