name: Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Stable Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
        
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all -- --deny warnings
